"""Compute every JudgeLab statistic from the committed compact dataset.

    python analyze.py            # writes data/stats.json
    python analyze.py --check    # exits 1 if data/stats.json is stale (used in CI)

Offline and deterministic (fixed bootstrap seed), so the published numbers can be
regenerated byte-for-byte by anyone.
"""
import argparse
import json
import pathlib
import sys

from judgelab.analysis import compute
from judgelab.data import load_compact

STATS = pathlib.Path(__file__).parent / "data" / "stats.json"


def fmt(e):
    return f"{e['value']:.3f} [{e['ci'][0]:.3f}, {e['ci'][1]:.3f}]"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if stats.json is out of date")
    args = ap.parse_args()

    stats = compute(**load_compact())
    text = json.dumps(stats, indent=2) + "\n"
    if args.check:
        if STATS.read_text(encoding="utf-8") != text:
            print("data/stats.json is stale: run `python analyze.py` and commit it.")
            return 1
        print("data/stats.json reproduces exactly from data/mtbench_compact.json.gz")
        return 0

    STATS.write_text(text, encoding="utf-8")
    hb = stats["human_baseline"]
    print(f"Joined pairs: {stats['n_joined_pairs']}  (95% CIs, question-clustered bootstrap)")
    print(f"  kappa, all verdicts        {fmt(stats['kappa_all'])}")
    print(f"  kappa, decisive only       {fmt(stats['kappa_nontie'])}")
    print(f"Same {hb['n_pairs']} multi-vote pairs, one judge vs one human:")
    print(f"  human vs human kappa       {fmt(hb['human_vs_human']['kappa'])}")
    print(f"  GPT-4 vs human kappa       {fmt(hb['gpt4_vs_human']['kappa'])}")
    print(f"Order-swap inconsistency     {fmt(stats['position']['inconsistent_rate'])}")
    v = stats["verbosity"]
    print(f"GPT-4 took the longer answer when it disagreed with humans "
          f"{fmt(v['disagreements_gpt4_took_longer'])}")
    g = stats["category_gap"]
    print(f"Kappa gap {g['strong']} - {g['weak']}: {fmt(g['kappa_difference'])}")
    print(f"Wrote {STATS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
